#! /bin/bash

RED='\033[0;31m'
CYAN='\033[36m'
BOLD='\033[1m'
RESET='\033[0m'

[ -z ${VIRTUAL_ENV+x} ] || {
    echo ""
    echo -e $RED $BOLD "[!] Entering nested debug shell is not allowed" $RESET
    exit 1
}

export NVIM_CONFIG_DEV_CONFIG_ROOT=$(dirname "$(realpath "$0")")
export NVIM_CONFIG_DEV_CACHE_ROOT=$NVIM_CONFIG_DEV_CONFIG_ROOT/nvim-cache
mkdir -p $NVIM_CONFIG_DEV_CACHE_ROOT/{share,state/log,cache,run,zdotdir}
# export PATH="$SCRIPT_DIR:$PATH"
export VIRTUAL_ENV=nvim-dev
echo ""
echo -e $CYAN $BOLD "[Note]: Please run \`nvim\` to launch nvim and enter \`exit\` to exit debug shell" $RESET

if [[ $1 == '--fish' ]]; then
    fish -C "function nvim --desc 'debug launch nvim'; NVIM_CONFIG_DEV=1 command nvim --clean -u $NVIM_CONFIG_DEV_CONFIG_ROOT/init.lua \$argv; end"
else
    ZDOTDIR=$NVIM_CONFIG_DEV_CACHE_ROOT/zdotdir
    [[ -f "$ZDOTDIR/.zshrc" ]] || {

cat > "$ZDOTDIR/.zshrc" <<EOF
[[ -f ~/.zshrc ]] && source ~/.zshrc
alias nvim="NVIM_CONFIG_DEV=1 command nvim --clean -u $NVIM_CONFIG_DEV_CONFIG_ROOT/init.lua"
EOF

    }
    ZDOTDIR="$ZDOTDIR" zsh
fi

echo ""
echo -e $CYAN $BOLD "[OK] Leaving debug shell..." $RESET
