#! /bin/bash

RED='\033[0;31m'
CYAN='\033[36m'
BOLD='\033[1m'
RESET='\033[0m'

[ -z ${VIRTUAL_ENV+x} ] || {
    echo ""
    echo -e $RED $BOLD "[!] Entering nested debug shell is not allowed" $RESET
    exit 1
}


export SCRIPT_DIR=$(dirname "$(realpath "$0")")
export TEST_ENV=$SCRIPT_DIR/nvim-cache
mkdir -p $TEST_ENV/{share,state,cache}
export PATH="$SCRIPT_DIR:$PATH"
export VIRTUAL_ENV=nvim-dev
echo ""
echo -e $CYAN $BOLD "[Note]: Please run \`vi\` to launch nvim and enter \`exit\` to exit debug shell" $RESET
ZDOTDIR=$(mktemp -d)
cat > "$ZDOTDIR/.zshrc" <<'EOF'
[[ -f ~/.zshrc ]] && source ~/.zshrc
alias vi="$(which nv)"
EOF
ZDOTDIR="$ZDOTDIR" zsh
rm -rf "$ZDOTDIR"
echo ""
echo -e $CYAN $BOLD "[OK] Leaving debug shell..." $RESET
