#! /bin/bash

RED='\033[0;31m'
CYAN='\033[36m'
BOLD='\033[1m'
RESET='\033[0m'

[ -z ${VIRTUAL_ENV+x} ] || {
    echo ""
    echo -e $RED $BOLD "[!] Entering nested debug shell is not allowed" $RESET
    exit 1
}

export NVIM_CONFIG_DEV_CONFIG_ROOT=$(dirname "$(realpath "$0")")
export NVIM_CONFIG_DEV_CACHE_ROOT=$NVIM_CONFIG_DEV_CONFIG_ROOT/nvim-cache
mkdir -p $NVIM_CONFIG_DEV_CACHE_ROOT/{share,state/log,cache,run,zdotdir}
export VIRTUAL_ENV=nvim-dev

export NVIM_CONFIG_DEV_BINARY=${NVIM_BINARY:-$(command -v nvim)}
# expand `~`
NVIM_CONFIG_DEV_BINARY="${NVIM_CONFIG_DEV_BINARY/#\~/$HOME}"

echo ""
[ -n "$NVIM_CONFIG_DEV_BINARY" ] || { echo -e $RED $BOLD "[!] nvim not found in PATH (set NVIM_BINARY)" $RESET; exit 1; }
[[ "$NVIM_CONFIG_DEV_BINARY" != /* ]] && { echo -e $RED $BOLD "[!] NVIM_BINARY must be an absolute path (got: \`$NVIM_CONFIG_DEV_BINARY\`)" $RESET; exit 1; }
echo -e $CYAN $BOLD "[Note]: Please run \`nvim\` to launch nvim and enter \`exit\` to exit debug shell" $RESET

if [[ $1 == '--fish' ]]; then
    fish -C "function nvim --desc 'debug launch nvim'; NVIM_CONFIG_DEV=1 command \"$NVIM_CONFIG_DEV_BINARY\" --clean -u \"$NVIM_CONFIG_DEV_CONFIG_ROOT\"/init.lua \$argv; end"
else
    ZDOTDIR=$NVIM_CONFIG_DEV_CACHE_ROOT/zdotdir
cat > "$ZDOTDIR/.zshrc" <<EOF
[[ -f ~/.zshrc ]] && source ~/.zshrc
alias nvim="NVIM_CONFIG_DEV=1 command \"$NVIM_CONFIG_DEV_BINARY\" --clean -u \"$NVIM_CONFIG_DEV_CONFIG_ROOT\"/init.lua"
EOF
    ZDOTDIR="$ZDOTDIR" zsh
fi

echo ""
echo -e $CYAN $BOLD "[OK] Leaving debug shell..." $RESET
