--- Simple lang specs
---@type LangSpec[]
return {
    { ft = 'asm', treesitter = true },
    { ft = 'astro', treesitter = true, formatter = { name = 'prettier' } },
    { ft = 'awk', treesitter = true },
    { ft = 'bash', treesitter = true },
    { ft = 'css', treesitter = true, formatter = { name = 'prettier' } },
    { ft = 'diff', treesitter = true },
    { ft = 'dockerfile', treesitter = true },
    { ft = 'dosini', treesitter = 'ini' },
    { ft = 'fish', treesitter = true },
    { ft = 'gitattributes', treesitter = true },
    { ft = 'gitcommit', treesitter = 'git_commit' },
    { ft = 'gitconfig', treesitter = 'git_config' },
    { ft = 'gitignore', treesitter = true },
    { ft = 'gitrebase', treesitter = 'git_rebase' },
    { ft = 'glsl', treesitter = true },
    { ft = 'html', treesitter = true, formatter = { name = 'prettier' } },
    { ft = 'javascript', treesitter = true },
    { ft = 'json', treesitter = true, formatter = { name = 'prettier' } },
    { ft = 'kdl', treesitter = true },
    { ft = 'latex', treesitter = true },
    { ft = 'llvm', treesitter = true },
    { ft = 'luadoc', treesitter = true },
    { ft = 'nginx', treesitter = true, formatter = { name = 'nginxfmt', packname = 'nginx-config-formatter' } },
    { ft = 'ninja', treesitter = true },
    { ft = 'query', treesitter = true },
    { ft = 'scheme', treesitter = true },
    { ft = 'tablegen', treesitter = true },
    { ft = 'toml', treesitter = true },
    { ft = 'typescript', treesitter = true },
    { ft = 'vim', treesitter = true },
    { ft = 'vimdoc', treesitter = true },
    { ft = 'yaml', treesitter = true },
}
